# Generated by Django 2.0.2 on 2018-02-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reg_data',
            new_name='reg_date',
        ),
    ]
